--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CortexPE/Hierarchy
branches:
  - master
projects:
  Hierarchy:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.2.1
      - src: SOF3/await-generator/await-generator
        version: ^2.2.0
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^1.0.0
      - src: CortexPE/Commando/Commando
        version: ~0.6 # change this to ^1.x.x when the time comes... we're using ~ because ~0.6 is >=0.6 <1.0.0
    lint:
      phpstan: false
...
