--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CortexPE/Hierarchy
branches:
- master
projects:
  Hierarchy:
    path: ""
    fullGzip: 9
    compressBuilds: false
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.2.0
      - src: SOF3/await-generator/await-generator
        version: ^2.2.0
      - src: dktapps/pmforms
        version: ^1.0.0
...
