--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CortexPE/Hierarchy
branches:
- master
projects:
  Hierarchy:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.2.0
      - src: SOFe/await-generator/AwaitGenerator
        version: ^2.2.0
...
