name: Hierarchy
main: CortexPE\Hierarchy\Hierarchy
version: 1.0.0
api: 3.0.0
load: POSTWORLD
author: CortexPE
description: "Role-based permission management system"
website: "https://CortexPE.xyz"

permissions:
  hierarchy:
    default: "false"
    description: "Main Hierarchy root permission node"
    children:
      hierarchy.list_roles:
        default: "op"
        description: "Allows to check role list"
      hierarchy.user_info:
        default: "true"
        description: "Allows to check role and permissions list"
      hierarchy.role:
        default: "false"
        description: "Allows role commands"
        children:
          hierarchy.role.add_permission:
            default: "op"
            description: "Allows the adding of permissions to a role"
          hierarchy.role.deny_permission:
            default: "op"
            description: "Allows the denying of permissions from a role"
          hierarchy.role.remove_permission:
            default: "op"
            description: "Allows the removal of permissions from a role"
          hierarchy.role.create:
            default: "op"
            description: "Allows the creation of roles"
          hierarchy.role.delete:
            default: "op"
            description: "Allows the deletion of roles"
          hierarchy.role.give:
            default: "op"
            description: "Allows the giving of roles"
          hierarchy.role.remove:
            default: "op"
            description: "Allows the sender to remove roles"
          hierarchy.role.options:
            default: "op"
            description: "Intermediate form for choosing players or permissions for a group"
          hierarchy.role.list_permissions:
            default: "op"
            description: "Allows to list the permissions for a role"
          hierarchy.role.list_players:
            default: "op"
            description: "Allows to list the players with a role"
