---
# Hierarchy DataSource options & settings
dataSource:
  # Available Types: json, sqlite3, mysql, yaml
  type: "sqlite3"

  # These settings will only apply when you chose json as dataSource type
  json:
    # Save JSON data files in a human-readable way
    prettyPrint: true

  # These settings will only apply when you chose sqlite3 as dataSource type
  sqlite3:
    # Database path
    dbPath: "hierarchy.sqlite"
    # The maximum number of simultaneous queries
    workerLimit: 1

  # These settings will only apply when you chose mysql as dataSource type
  mysql:
    host: "localhost"
    user: "hierarchy"
    password: "youShallNotPass"
    database: "hierarchy"
    schema: "hierarchy"
    # The maximum number of simultaneous queries
    workerLimit: 2 # Increase the value if you have a slow connection to the MySQL server

# Allow OPs to bypass permission checks
superAdminOPs: false
...