---
# Hierarchy Role & Permission sets DataSource options & settings
roleDataSource:
  # Available Types: json, yaml
  type: "yaml"

  # These settings will only apply when you chose json as dataSource type
  json:
    # Save JSON data files in a human-readable way
    prettyPrint: true

# Hierarchy Member DataSource options & settings
memberDataSource:
  # Available Types: json, sqlite3, mysql, yaml
  type: "sqlite3"

  # These settings will only apply when you chose sqlite3 as dataSource type
  sqlite3:
    # Database path
    dbPath: "members.sqlite"
    # The maximum number of simultaneous queries
    workerLimit: 1

  # These settings will only apply when you chose mysql as dataSource type
  mysql:
    host: "localhost"
    username: "hierarchy"
    password: "youShallNotPass"
    database: "hierarchyMembers"
    schema: "hierarchyMembers"
    # The maximum number of simultaneous queries
    workerLimit: 2 # Increase the value if you have a slow connection to the MySQL server

# Allow OPs to bypass permission checks
superAdminOPs: false

configVersion: 1.6
...